Improved the build script once more
Signed-off-by: Wilson Brenna <wbrenna@uwaterloo.ca>

diff --git a/src/pdf/popplerdirect/workaround/workaround.sh.in b/src/pdf/popplerdirect/workaround/workaround.sh.in
--- a/src/pdf/popplerdirect/workaround/workaround.sh.in
+++ b/src/pdf/popplerdirect/workaround/workaround.sh.in
@@ -7,6 +7,7 @@
 # for later use
 
 poppler_version="0.24.1"
+scriptname=`basename $0`
 
 abs_top_srcdir="@abs_top_srcdir@"
 abs_top_builddir="@abs_top_builddir@"
@@ -15,6 +16,25 @@ enable_libopenjpeg="@enable_libopenjpeg@"
 poppler_srcdir="${abs_top_srcdir}/src/pdf/popplerdirect/poppler-${poppler_version}"
 poppler_dir="${abs_top_builddir}/src/pdf/popplerdirect"
 poppler_builddir="${poppler_dir}/poppler-${poppler_version}_build"
+
+create_link()
+{
+  sourcedir=$1
+  targetdir=$2
+  filename=$3
+
+  if [ ! -e "${sourcedir}/${filename}" ]; then
+    echo "Error in ${scriptname}: Can't create symbolic link:"
+    echo "${sourcedir}/${filename} does not exist"
+    echo
+    exit 1
+  fi
+
+  if [ ! -e "${targetdir}/${filename}" ]; then
+    rm -f "${targetdir}/${filename}"
+    ln -s "${sourcedir}/${filename}" "${targetdir}/${filename}"
+  fi
+}
 
 build()
 {
@@ -40,9 +60,9 @@ build()
 
   make
 
-  ln -s "${poppler_builddir}/poppler/.libs/libpoppler.a" "${poppler_dir}"
-  ln -s "${poppler_builddir}/glib/.libs/libpoppler-glib.a" "${poppler_dir}"
-  ln -s "${poppler_builddir}/poppler/poppler-config.h" "${poppler_dir}"
+  create_link "${poppler_builddir}/poppler/.libs" "${poppler_dir}" "libpoppler.a"
+  create_link "${poppler_builddir}/glib/.libs" "${poppler_dir}" "libpoppler-glib.a"
+  create_link "${poppler_builddir}/poppler" "${poppler_dir}" "poppler-config.h"
 }
 
 clean()
