Add several clang-format versions in CI check

diff --git a/azure-pipelines/clang-format-applied.yml b/azure-pipelines/clang-format-applied.yml
--- a/azure-pipelines/clang-format-applied.yml
+++ b/azure-pipelines/clang-format-applied.yml
@@ -20,13 +20,20 @@ stages:
     pool:
       vmImage: 'ubuntu-20.04'
     displayName: 'Test for correct Clang formatting'
+    variables:
+    - name: CLANG_FORMAT_VERSIONS
+      value: "15 16"
     steps:
     - checkout: self
     - bash: |
         wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
-        sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal main"
+        for VERSION in $(CLANG_FORMAT_VERSIONS); do
+          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-$VERSION main"
+        done
         sudo apt-get update
-        sudo apt-get install -y clang-format
+        for VERSION in $(CLANG_FORMAT_VERSIONS); do
+          sudo apt-get install -y clang-format-$VERSION
+        done
       displayName: 'Install clang-format'
     - bash: |
         git config --global clangFormat.extensions "c,h,cpp,hpp,hxx,cxx,cc,hh'"
@@ -43,5 +50,11 @@ stages:
         [[ -z "$BASE_COMMIT" ]] && { echo "Error: BASE_COMMIT is empty" ; exit 1; }
         git fetch origin $BASE_COMMIT
         
-        git clang-format --diff $BASE_COMMIT --
+        for VERSION in $(CLANG_FORMAT_VERSIONS); do
+          echo "Testing clang-format-$VERSION"
+          git clang-format-$VERSION --diff $BASE_COMMIT -- && { echo "Success: changes are compatible with clang-format-$VERSION"; exit 0; }
+        done
+        # Failure: None of the allowed clang-format versions validated the changes
+        echo "Error: changes are not compatible with any of the allowed clang-format versions: $CLANG_FORMAT_VERSIONS"
+        exit 1
       displayName: 'Run clang-format on modified files'
